In [35]:
data = '''
Stage,Stage time (s),Category,Packet Size,Sampling Rate
Boost,30,Battery/Environment,48,1,
Boost,30,ADC,8,1000
Boost,30,IMU,88,1000
Apogee,5,Battery/Environment,48,1
Apogee,5,ADC,8,5000
Apogee,5,IMU,88,1000
Descent,240,Battery/Environment,48,1
Descent,240,ADC,8,100
Descent,240,IMU,88,100
'''

In [14]:
import pandas as pd
import io

In [33]:
df = pd.read_csv(io.StringIO(data))

In [42]:
df.set_index(["Stage", "Stage time (s)", "Category"])

                                            Packet Size  Sampling Rate  Byte/s
Stage   Stage time (s) Category
Boost   30             Battery/Environment           48              1     NaN
                       ADC                            8           1000     NaN
                       IMU                           88           1000     NaN
Apogee  5              Battery/Environment           48              1     NaN
                       ADC                            8           5000     NaN
                       IMU                           88           1000     NaN
Descent 240            Battery/Environment           48              1     NaN
                       ADC                            8            100     NaN
                       IMU                           88            100     NaN

In [46]:
df["Byte/s"] = df["Packet Size"] * df["Sampling Rate"]

In [51]:
df

,Stage,Stage time (s),Category,Packet Size,Sampling Rate,Byte/s
0,Boost,30,Battery/Environment,48,1,48
1,Boost,30,ADC,8,1000,8000
2,Boost,30,IMU,88,1000,88000
3,Apogee,5,Battery/Environment,48,1,48
4,Apogee,5,ADC,8,5000,40000
5,Apogee,5,IMU,88,1000,88000
6,Descent,240,Battery/Environment,48,1,48
7,Descent,240,ADC,8,100,800
8,Descent,240,IMU,88,100,8800

In [59]:
inner = df[["Stage","Byte/s"]]
outer = df[["Stage","Byte/s"]].groupby("Stage").sum()

In [60]:
inner

     Stage  Byte/s
0    Boost      48
1    Boost    8000
2    Boost   88000
3   Apogee      48
4   Apogee   40000
5   Apogee   88000
6  Descent      48
7  Descent     800
8  Descent    8800